//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kora_Today.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public Club()
        {
            this.Histories = new HashSet<History>();
        }
    
        public int ClubId { get; set; }
        public string ClubName { get; set; }
        public string ClubImage { get; set; }
        public int LeagueId { get; set; }
        public string Played { get; set; }
        public string Won { get; set; }
        public string Drawn { get; set; }
        public string Lost { get; set; }
        public string GoalsFor { get; set; }
        public string GoalsAgainst { get; set; }
        public string GoalsDifference { get; set; }
        public string Points { get; set; }
    
        public virtual League League { get; set; }
        public virtual ICollection<History> Histories { get; set; }
    }
}
