//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kora_Today.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int HistoryId { get; set; }
        public string HistoryTitle { get; set; }
        public string HistoryContent { get; set; }
        public string HistoryTime { get; set; }
        public string HistoryImage { get; set; }
        public int ClubId { get; set; }
    
        public virtual Club Club { get; set; }
    }
}
