//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kora_Today.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class League
    {
        public League()
        {
            this.Clubs = new HashSet<Club>();
            this.Players = new HashSet<Player>();
        }
    
        public int LeagueId { get; set; }
        public string LeagueName { get; set; }
        public string LeagueImage { get; set; }
    
        public virtual ICollection<Club> Clubs { get; set; }
        public virtual ICollection<Player> Players { get; set; }
    }
}
