//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kora_Today.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Match
    {
        public Match()
        {
            this.MatchTvs = new HashSet<MatchTv>();
            this.MatchDetails = new HashSet<MatchDetail>();
        }
    
        public int MatchId { get; set; }
        public string MatchHome { get; set; }
        public string MatchAway { get; set; }
        public string MatchHomeImage { get; set; }
        public string MatchAwayImage { get; set; }
        public string MatchResult { get; set; }
        [DataType(DataType.Date)]
        public string MatchDate { get; set; }
        [DataType(DataType.Time)]
        public string MatchTime { get; set; }
        public string MatchStatus { get; set; }
        public string MatchLeague { get; set; }
    
        public virtual ICollection<MatchTv> MatchTvs { get; set; }
        public virtual ICollection<MatchDetail> MatchDetails { get; set; }
    }
}
