//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kora_Today.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int SliderId { get; set; }
        public string SliderImage { get; set; }
        public string SliderLink { get; set; }
    }
}
